//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIO.FinancialWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:invoice", ConfigurationName="FinancialWebService.invoicePortType")]
    public interface invoicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoice#createInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string createInvoice(string token, string authority, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoice#createInvoice", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> createInvoiceAsync(string token, string authority, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoice#payTheInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string payTheInvoice(string invoiceId, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoice#payTheInvoice", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> payTheInvoiceAsync(string invoiceId, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoice#getAllInvoiceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AIO.FinancialWebService.invoiceList getAllInvoiceList(string nick, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoice#getAllInvoiceList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AIO.FinancialWebService.invoiceList> getAllInvoiceListAsync(string nick, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoice#getAllInvoiceListSplit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAllInvoiceListSplit(string nick, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:invoice#getAllInvoiceListSplit", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAllInvoiceListSplitAsync(string nick, string token, string authority);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:invoice")]
    public partial class invoiceList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private invoice invoiceField;
        
        /// <remarks/>
        public invoice invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
                this.RaisePropertyChanged("invoice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:invoice")]
    public partial class invoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nickField;
        
        private string dateField;
        
        private string timeField;
        
        private string priceField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
                this.RaisePropertyChanged("nick");
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface invoicePortTypeChannel : AIO.FinancialWebService.invoicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class invoicePortTypeClient : System.ServiceModel.ClientBase<AIO.FinancialWebService.invoicePortType>, AIO.FinancialWebService.invoicePortType {
        
        public invoicePortTypeClient() {
        }
        
        public invoicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public invoicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public invoicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public invoicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string createInvoice(string token, string authority, string time) {
            return base.Channel.createInvoice(token, authority, time);
        }
        
        public System.Threading.Tasks.Task<string> createInvoiceAsync(string token, string authority, string time) {
            return base.Channel.createInvoiceAsync(token, authority, time);
        }
        
        public string payTheInvoice(string invoiceId, string token, string authority) {
            return base.Channel.payTheInvoice(invoiceId, token, authority);
        }
        
        public System.Threading.Tasks.Task<string> payTheInvoiceAsync(string invoiceId, string token, string authority) {
            return base.Channel.payTheInvoiceAsync(invoiceId, token, authority);
        }
        
        public AIO.FinancialWebService.invoiceList getAllInvoiceList(string nick, string token, string authority) {
            return base.Channel.getAllInvoiceList(nick, token, authority);
        }
        
        public System.Threading.Tasks.Task<AIO.FinancialWebService.invoiceList> getAllInvoiceListAsync(string nick, string token, string authority) {
            return base.Channel.getAllInvoiceListAsync(nick, token, authority);
        }
        
        public string getAllInvoiceListSplit(string nick, string token, string authority) {
            return base.Channel.getAllInvoiceListSplit(nick, token, authority);
        }
        
        public System.Threading.Tasks.Task<string> getAllInvoiceListSplitAsync(string nick, string token, string authority) {
            return base.Channel.getAllInvoiceListSplitAsync(nick, token, authority);
        }
    }
}
