//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIO.FinancialWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:financial", ConfigurationName="FinancialWebService.financialPortType")]
    public interface financialPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:financial#createInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string createInvoice(string token, string authority, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:financial#createInvoice", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> createInvoiceAsync(string token, string authority, string time);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:financial#payTheInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string payTheInvoice(string invoiceId, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:financial#payTheInvoice", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> payTheInvoiceAsync(string invoiceId, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:financial#getAllInvoiceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AIO.FinancialWebService.financialList getAllInvoiceList(string nick, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:financial#getAllInvoiceList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AIO.FinancialWebService.financialList> getAllInvoiceListAsync(string nick, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:financial#getAllInvoiceListSplit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getAllInvoiceListSplit(string nick, string token, string authority);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:financial#getAllInvoiceListSplit", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getAllInvoiceListSplitAsync(string nick, string token, string authority);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:financial")]
    public partial class financialList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private financial financialField;
        
        /// <remarks/>
        public financial financial {
            get {
                return this.financialField;
            }
            set {
                this.financialField = value;
                this.RaisePropertyChanged("financial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:financial")]
    public partial class financial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nickField;
        
        private string dateField;
        
        private string timeField;
        
        private string priceField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
                this.RaisePropertyChanged("nick");
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        public string price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface financialPortTypeChannel : AIO.FinancialWebService.financialPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class financialPortTypeClient : System.ServiceModel.ClientBase<AIO.FinancialWebService.financialPortType>, AIO.FinancialWebService.financialPortType {
        
        public financialPortTypeClient() {
        }
        
        public financialPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public financialPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public financialPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public financialPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string createInvoice(string token, string authority, string time) {
            return base.Channel.createInvoice(token, authority, time);
        }
        
        public System.Threading.Tasks.Task<string> createInvoiceAsync(string token, string authority, string time) {
            return base.Channel.createInvoiceAsync(token, authority, time);
        }
        
        public string payTheInvoice(string invoiceId, string token, string authority) {
            return base.Channel.payTheInvoice(invoiceId, token, authority);
        }
        
        public System.Threading.Tasks.Task<string> payTheInvoiceAsync(string invoiceId, string token, string authority) {
            return base.Channel.payTheInvoiceAsync(invoiceId, token, authority);
        }
        
        public AIO.FinancialWebService.financialList getAllInvoiceList(string nick, string token, string authority) {
            return base.Channel.getAllInvoiceList(nick, token, authority);
        }
        
        public System.Threading.Tasks.Task<AIO.FinancialWebService.financialList> getAllInvoiceListAsync(string nick, string token, string authority) {
            return base.Channel.getAllInvoiceListAsync(nick, token, authority);
        }
        
        public string getAllInvoiceListSplit(string nick, string token, string authority) {
            return base.Channel.getAllInvoiceListSplit(nick, token, authority);
        }
        
        public System.Threading.Tasks.Task<string> getAllInvoiceListSplitAsync(string nick, string token, string authority) {
            return base.Channel.getAllInvoiceListSplitAsync(nick, token, authority);
        }
    }
}
